# LinkedIn/web cross-reference results for Country.
# key = "Company||FullName"  ->  (country, confidence, signal)
# confidence: "Verified" = matching profile showed a country signal (explicit location
#             or country-coded LinkedIn subdomain); "Assumed" = fell back to HQ country.
# Allowed countries (confirmed by user): United Kingdom, France, Germany,
#             Netherlands, Spain, Portugal.

OVERRIDES = {
    # ---- HSBC ----
    "HSBC||Hazem El Taha": ("United Kingdom", "Assumed", "London conference activity; no explicit LinkedIn location"),
    "HSBC||Laura Morgante": ("United Kingdom", "Assumed", "no clean profile match"),
    "HSBC||Andreas Fenneker": ("Germany", "Verified", "based in Dusseldorf, Germany; HSBC Germany, Associate Director Marketing"),
    "HSBC||Steve Thomas": ("United Kingdom", "Verified", "profile: based in London"),
    "HSBC||Nicole German": ("United Kingdom", "Assumed", "HSBC CIB (London-based team); no explicit location"),
    "HSBC||Alex Leay": ("United Kingdom", "Verified", "Head of UK Marketing, HSBC Asset Management"),
    "HSBC||William Barraclough": ("United Kingdom", "Verified", "profile: located in United Kingdom"),

    # ---- Barclays ----
    "Barclays||Ben Harding": ("United Kingdom", "Assumed", "no clean profile match; Barclays UK"),
    "Barclays||Dolika Dhar": ("United Kingdom", "Verified", "uk.linkedin.com/in/dolika-dhar; VP Compliance"),
    "Barclays||Fred Doyhamboure": ("United Kingdom", "Verified", "uk.linkedin.com/in/fred-doyhamboure; Markets Compliance"),
    "Barclays||Amit Singh": ("United Kingdom", "Verified", "TheOrg Barclays Corporate Banking; exact title match, London-based role"),
    "Barclays||Magnus Deuling": ("United Kingdom", "Assumed", "profile matched (MarketsOne, Barclays IB) but no explicit location"),
    "Barclays||Lauren Stewart": ("United Kingdom", "Assumed", "no clean profile match; Barclays UK"),
    "Barclays||Priya Mallinson": ("United Kingdom", "Verified", "uk.linkedin.com/in/priyamallinson; exact title match"),

    # ---- NatWest Group ----
    "NatWest Group||Eleanor Whittaker": ("United Kingdom", "Verified", "profile: based in London"),
    "NatWest Group||Maria Lagutina": ("United Kingdom", "Verified", "uk.linkedin.com/in/marialagutina; based in London, GB"),
    "NatWest Group||Wendy Redshaw": ("United Kingdom", "Verified", "NatWest Retail CDIO, London-based; London Tech Week speaker"),
    "NatWest Group||Robyn Johnston": ("United Kingdom", "Verified", "profile: based in London (CIB Marketing)"),
    "NatWest Group||Marty Carroll": ("United Kingdom", "Verified", "profile: based in London, GB"),
    "NatWest Group||Dasha Lukiniha": ("United Kingdom", "Verified", "profile: based in London"),
    "NatWest Group||Nicky Mackrell": ("United Kingdom", "Verified", "uk.linkedin.com; based in London"),
    "NatWest Group||Matthew Harwood": ("United Kingdom", "Verified", "profile: located in United Kingdom"),
    "NatWest Group||Kate Litler": ("United Kingdom", "Verified", "30-yr NatWest/RBS UK career; UK-based"),
    "NatWest Group||Grant Thomas": ("United Kingdom", "Verified", "profile: London Area, United Kingdom"),
    "NatWest Group||Tanvi Gokhali": ("United Kingdom", "Verified", "uk.linkedin.com; based in London, GB"),
    "NatWest Group||Amanda Scott": ("United Kingdom", "Assumed", "no clean profile match; NatWest UK"),

    # ---- Lloyds Banking Group (UK-only bank) ----
    "Lloyds Banking Group||Aimee Hood": ("United Kingdom", "Assumed", "no clean profile match; Lloyds is UK-only"),
    "Lloyds Banking Group||Laurie Hodge": ("United Kingdom", "Assumed", "no clean profile match; Lloyds is UK-only"),
    "Lloyds Banking Group||Jay Safdar": ("United Kingdom", "Assumed", "not searched individually; Lloyds is UK-only"),
    "Lloyds Banking Group||Ben Logan": ("United Kingdom", "Assumed", "ambiguous profile; Lloyds is UK-only"),
    "Lloyds Banking Group||Seena Samani": ("United Kingdom", "Verified", "uk.linkedin.com/in/seena-s; Head of Marketing Effectiveness"),
    "Lloyds Banking Group||Ella Davis": ("United Kingdom", "Verified", "uk.linkedin.com/in/ella-davis; Lloyds"),
    "Lloyds Banking Group||Sangeetha Narasimhan": ("United Kingdom", "Verified", "uk.linkedin.com/in/sangeethacn; UK Companies House officer"),

    # ---- Santander (Spain HQ, multinational) ----
    "Santander||Idoia Muguruza": ("Spain", "Verified", "profile: Greater Madrid Metropolitan Area"),
    "Santander||Antonio Herranz": ("Spain", "Verified", "profile: Madrid, Spain"),
    "Santander||Bernabe Mohedano Cuadrado": ("Spain", "Verified", "es.linkedin.com; Madrid; Santander Espana"),
    "Santander||Ana Donaire": ("Spain", "Verified", "profile: Madrid, Spain; Head of Brand & Corporate Marketing"),
    "Santander||Silvia Merino Prieto": ("Spain", "Verified", "profile: Madrid, Spain; Santander CIB"),
    "Santander||Andrea Moran Arnedo": ("Spain", "Verified", "es.linkedin.com; Spain-based, Banco Santander"),
    "Santander||Jorge Varela": ("Spain", "Verified", "profile: Madrid, Spain"),
    "Santander||David Meza Ayala": ("Spain", "Assumed", "no clean profile match; Santander Spain AI role"),
    "Santander||Adam Beardmore": ("Spain", "Assumed", "no clean profile match; HQ default (may be UK - unverified)"),

    # ---- BBVA (Spain HQ, multinational; strong Italy/Mexico presence) ----
    "BBVA||Luis Calleja": ("Spain", "Verified", "profile: Madrid, Spain"),
    "BBVA||Miguel Alcala": ("Spain", "Verified", "profile: Madrid, Spain; BBVA Spark Spain since 2022"),
    "BBVA||Horacio Ballestrin": ("Spain", "Verified", "profile: based in Spain (ex-BBVA Mexico)"),
    "BBVA||David Arconada": ("Spain", "Verified", "profile: Boadilla del Monte, Madrid (BBVA HQ)"),
    "BBVA||Sofia Rodriguez-Sahagun": ("Spain", "Verified", "profile: Greater Madrid Metropolitan Area"),
    "BBVA||Walter Rizzi": ("Italy", "Verified", "Milan, Italy; Country Manager BBVA Italy (NOTE: outside user 6-country list)"),
    "BBVA||Nicola Cecchetto": ("Italy", "Verified", "Milan, Italy; Head of Legal BBVA Italy (NOTE: outside user 6-country list)"),
    "BBVA||Martin Eizaga": ("Italy", "Assumed", "CMO/Head of Product BBVA Digital Banking Italy; likely Italy, some es.linkedin activity (may be Madrid-based)"),
    "BBVA||Elsa Garcia": ("Spain", "Verified", "es.linkedin.com/in/elsa-moya-garcia; directora BBVA"),
    "BBVA||Ignacio Gomez": ("Spain", "Verified", "profile: Greater Madrid Metropolitan Area; BBVA CIB"),
    "BBVA||Oscar Gomez": ("Spain", "Verified", "profile: Madrid, Spain (Oscar Moya Gomez)"),
    "BBVA||Ramon Calderon": ("Spain", "Verified", "es.linkedin; Head Digital Sales & Marketing BBVA Spain"),
    "BBVA||Alfonso Iglesias": ("Spain", "Verified", "profile: Greater Madrid Metropolitan Area"),

    # ---- BNP Paribas (France HQ, multinational) ----
    "BNP Paribas||Damien Cogez": ("France", "Verified", "profile: Paris, France"),
    "BNP Paribas||Tutku Salihoglu": ("France", "Verified", "fr.linkedin.com; BNP Paribas Cardif (Paris)"),
    "BNP Paribas||Mitra Moinfar": ("France", "Verified", "profile: Paris; leads Mobile Journey team"),
    "BNP Paribas||Romain Rossetti": ("France", "Verified", "profile: Greater Paris Metropolitan Region"),
    "BNP Paribas||Lisa Bush": ("United Kingdom", "Verified", "profile: London, GB; BNP Paribas AM Northern Europe"),
    "BNP Paribas||Atman Bentahar": ("France", "Verified", "fr.linkedin.com; BNP Paribas Omnichannel"),
    "BNP Paribas||Soufiane Bachiri": ("France", "Verified", "profile: Neuilly-sur-Seine (Paris)"),
    "BNP Paribas||Charlotte Cren": ("France", "Verified", "profile: Paris, France"),
    "BNP Paribas||Deborrah Flament": ("France", "Verified", "profile: Greater Paris Metropolitan Region"),

    # ---- Societe Generale (France HQ) ----
    "Societe Generale||Onsi Kahlaoui": ("France", "Verified", "profile: Suresnes (Paris area)"),
    "Societe Generale||Giorgio Bellati": ("France", "Verified", "profile: Greater Paris Metropolitan Region"),
    "Societe Generale||Pierre-Emmanuel Fraisse": ("France", "Verified", "profile: Villeneuve-d'Ascq, France"),
    "Societe Generale||Tiphaine Massard": ("France", "Verified", "profile: Greater Paris Metropolitan Region"),
    "Societe Generale||Salma Radi": ("France", "Verified", "profile: Paris; SGCIB"),
    "Societe Generale||Laetitia Bianchi": ("France", "Verified", "profile: Paris, FR; SGCIB Global Markets"),

    # ---- Credit Agricole (France HQ) ----
    "Credit Agricole||Stephanie Vicat": ("France", "Verified", "fr.linkedin; Groupe Credit Agricole (France)"),
    "Credit Agricole||Julien Provost-Langot": ("France", "Verified", "fr.linkedin; CA Consumer Finance, Paris"),
    "Credit Agricole||Nicolas Renaut": ("France", "Verified", "profile: Paris; Credit Agricole SA"),
    "Credit Agricole||Shivani Bhagat": ("France", "Verified", "fr.linkedin; CA CIB / CACEIS (Paris)"),
    "Credit Agricole||Marie Gourche": ("France", "Verified", "profile: Le Mesnil-Saint-Denis (Paris region)"),
    "Credit Agricole||Vincent Giraudel": ("France", "Verified", "profile: Montrouge (CA SA HQ); now CA Ile-de-France"),
    "Credit Agricole||Yani Arkat": ("France", "Verified", "profile: Greater Paris Metropolitan Region"),
    "Credit Agricole||Julian Nastase": ("United Kingdom", "Verified", "uk.linkedin.com/in/iuliann; Business Manager CA-CIB London"),
    "Credit Agricole||James Hanscombe": ("France", "Assumed", "no clean match; likely CA-CIB London/UK - UNCONFIRMED, retry"),

    # ---- ING Group (Netherlands HQ) ----
    "ING Group||Adis Tutundzic": ("Netherlands", "Verified", "profile: Netherlands"),
    "ING Group||Michel Drupsteen": ("Netherlands", "Verified", "profile: Amsterdam, NL"),
    "ING Group||Yvon Martin": ("Netherlands", "Verified", "profile: Amsterdam (was ING France, now global brand in NL)"),
    "ING Group||Arjen Hoekstra": ("Netherlands", "Verified", "nl.linkedin.com/in/aohoekstra; ING Business Banking NL"),
    "ING Group||Willem Speelman": ("Netherlands", "Verified", "profile: Amsterdam, Netherlands"),
    "ING Group||Amit Vats": ("Netherlands", "Assumed", "no clean match; ING NL role, @ing.com"),
    "ING Group||Robert Rugebregt": ("Netherlands", "Assumed", "no clean profile match; ING (NL)"),
    "ING Group||Omer Cerrahoglu": ("Netherlands", "Verified", "profile: Amsterdam, Netherlands; ING NL"),
    "ING Group||Jaap Burggraaff": ("Netherlands", "Verified", "profile: Geldermalsen, Netherlands"),
    "ING Group||Niels Stroeve": ("Netherlands", "Verified", "nl.linkedin.com/in/stroeve; Netherlands"),
    "ING Group||Arjen Noordeman": ("Netherlands", "Verified", "profile: Amsterdam, Netherlands"),
    "ING Group||Aksidan Kukalev": ("Netherlands", "Assumed", "not searched (search cap); ING NL HQ default"),
    "ING Group||Murat Ayrancioglu": ("Netherlands", "Assumed", "not searched (search cap); ING NL HQ default"),

    # ---- ABN AMRO (Netherlands HQ) ----
    "ABN AMRO||Marijke Goudberg": ("Netherlands", "Verified", "profile: Leiden, Netherlands"),
    "ABN AMRO||Benko Vermolen": ("Netherlands", "Assumed", "no clean LinkedIn match; Dutch (NL running/social profiles)"),
    "ABN AMRO||Yorick Naeff": ("Netherlands", "Verified", "profile: Amsterdam; Head of Innovation ABN AMRO"),
    "ABN AMRO||Lisa Dubach": ("Netherlands", "Verified", "profile: Amsterdam, NH, NL"),
    "ABN AMRO||Erik Wijnen": ("Netherlands", "Verified", "profile: Amsterdam"),
    "ABN AMRO||Aude Josset": ("France", "Verified", "profile: Paris, FR; ABN AMRO Investment Solutions"),

    # ---- Millennium BCP (Portugal HQ) ----
    "Millennium BCP||Joao Trigueiros": ("Portugal", "Verified", "profile: Lisbon"),
    "Millennium BCP||Andre Correia": ("Portugal", "Verified", "profile: Lisbon, PT"),
    "Millennium BCP||Pedro Mendes": ("Portugal", "Verified", "profile: Lisbon"),
    "Millennium BCP||Miguel Garcia Almeida": ("Portugal", "Assumed", "no explicit location; Millennium BCP Portugal team"),
    "Millennium BCP||Jose Nunes": ("Portugal", "Verified", "profile: Oeiras (Lisbon area)"),
    "Millennium BCP||Filipe Marques": ("Portugal", "Verified", "profile: Lisbon, Portugal"),
    "Millennium BCP||Rachel Ferreira": ("Portugal", "Assumed", "no clean match; BCP is Portugal-domestic"),
    "Millennium BCP||Isabel Santos": ("Portugal", "Verified", "pt.linkedin; Lisbon, PT"),
    "Millennium BCP||Fernanda Aguiar": ("Portugal", "Verified", "pt.linkedin; Lisbon Metropolitan Area"),
    "Millennium BCP||Pedro Beija": ("Portugal", "Verified", "pt.linkedin; Lisbon, Portugal"),
    "Millennium BCP||Joao Jesus": ("Portugal", "Assumed", "BCP DATO (Lisbon); no explicit location on profile"),
    "Millennium BCP||Jose Farinha": ("Portugal", "Assumed", "no clean match; BCP is Portugal-domestic"),

    # ---- Deutsche Bank (Germany HQ, very multinational) ----
    "Deutsche Bank||Snehal Pandya": ("United Kingdom", "Verified", "uk.linkedin.com/in/sampandya; DB"),
    "Deutsche Bank||Stephen Bell": ("United Kingdom", "Assumed", "MD Global Head FIC/Securities Svcs Ops; ex-JPM EMEA London - likely London, unconfirmed"),
    "Deutsche Bank||Raquel Carrillo": ("Spain", "Verified", "profile: Madrid; DB Espana Head of Marketing"),
    "Deutsche Bank||Merle Meier-Holsten": ("Germany", "Verified", "profile: Frankfurt, Germany"),
    "Deutsche Bank||Mina Saidze": ("Germany", "Verified", "profile: Germany (Berlin)"),
    "Deutsche Bank||Nicki Saini": ("United Kingdom", "Assumed", "DB Event & Partnership Marketing team is London-based; unconfirmed"),
    "Deutsche Bank||Marcel Everts": ("Germany", "Assumed", "no explicit location; HQ default (Dutch name - could be NL)"),
    "Deutsche Bank||Brigitte Koetting": ("Germany", "Verified", "profile: Hesse, Germany (Frankfurt)"),
    "Deutsche Bank||Kim Kranz": ("Germany", "Verified", "profile: Munich, Germany"),
    "Deutsche Bank||Holger Fischer": ("Germany", "Assumed", "no clean match; DB Brand Strategy (de)"),
    "Deutsche Bank||Morgane Constanty": ("United Kingdom", "Assumed", "speaks at London fintech events; DB AI/Corporate Bank - likely London, unconfirmed"),
    "Deutsche Bank||Marcin Belinski": ("Germany", "Verified", "de.linkedin.com/in/marcin-belinski; DB Product Leader"),
    "Deutsche Bank||Priyanka Dayal": ("Germany", "Assumed", "no clean location; DB Global Marketing (HQ default)"),
    "Deutsche Bank||David Dommel": ("Germany", "Verified", "profile: Berlin; DB Head of Performance Marketing"),
    "Deutsche Bank||Lisa Barahona": ("Germany", "Assumed", "no email/no clean match; DB (HQ default)"),

    # ---- CaixaBank (Spain HQ, Barcelona) ----
    "CaixaBank||Carles Aznar Carrique": ("Spain", "Assumed", "no clean match; CaixaBank (Barcelona)"),
    "CaixaBank||Jordi Guaus": ("Spain", "Verified", "profile: Greater Barcelona Metropolitan Area"),
    "CaixaBank||Angels Valls Benitez": ("Spain", "Verified", "profile: Barcelona, Spain"),
    "CaixaBank||Joan Gaitx": ("Spain", "Verified", "profile: Greater Barcelona Metropolitan Area"),
    "CaixaBank||German Mazza": ("Spain", "Verified", "profile: Barcelona, Spain (German Montero Mazza)"),
    "CaixaBank||Sergio Ruiz": ("Spain", "Verified", "profile: Madrid; CaixaBank Design Lead"),
    "CaixaBank||Eduardo Mallart": ("Spain", "Verified", "profile: Barcelona Area, Spain"),
    "CaixaBank||Genis Barnich Fonolla": ("Spain", "Verified", "profile: Barcelona, Spain"),
    "CaixaBank||Sergio Ponce": ("Spain", "Verified", "profile: Madrid, Spain (Sergio Gutierrez Ponce)"),
    "CaixaBank||Ruben Morin Martin": ("Spain", "Verified", "profile: Greater Madrid; CaixaBank Tech"),
    "CaixaBank||Carla Manonelles": ("Spain", "Verified", "profile: Catalonia, Spain"),
    "CaixaBank||Ignacio Molinero": ("Spain", "Verified", "profile: Madrid, Spain"),

    # ---- Revolut (UK HQ, very international workforce) ----
    "Revolut||Madeline White": ("United Kingdom", "Verified", "profile: United Kingdom"),
    "Revolut||Kuba Fast": ("United Kingdom", "Assumed", "CEO Revolut Bank UAB (Vilnius, LITHUANIA entity); ex-Chase UK - physical base ambiguous UK/Lithuania - NEEDS REVIEW"),
    "Revolut||Marco Tracogna": ("Spain", "Verified", "profile: Barcelona, Spain"),
    "Revolut||Eleanor Taylor": ("United Kingdom", "Assumed", "Revolut UK creative marketing; a Lisbon profile also exists - unconfirmed"),
    "Revolut||Vladimir Kovtun": ("United Kingdom", "Assumed", "no clean Revolut match; Revolut HQ (UK) default"),
    "Revolut||Sofya Tretyakova": ("United Kingdom", "Verified", "profile: London, GB"),
    "Revolut||Leila Sakhnini": ("United Kingdom", "Verified", "uk.linkedin.com/in/leilasakhnini"),
    "Revolut||Theau Guillot": ("France", "Verified", "profile: Paris; based remotely from France"),
    "Revolut||Edouard Daunizeau": ("United Kingdom", "Verified", "profile: London, GB (South Hackney)"),
    "Revolut||Sonia Calderon": ("Spain", "Verified", "profile: Greater Barcelona Metropolitan Area (Sonia Rosales Calderon)"),
    "Revolut||Sergei Puzin": ("United Kingdom", "Assumed", "no explicit location; Revolut HQ (UK) default"),
    "Revolut||Irina Zhukova": ("Germany", "Verified", "de.linkedin.com/in/irina-zhukova; ex-Freeletics (Munich)"),
    "Revolut||Wes Brannigan": ("United Kingdom", "Verified", "profile: London, England, UK; Head of Ops Revolut UK"),
    "Revolut||Cedric Sevin": ("Spain", "Verified", "profile: Madrid"),
    "Revolut||Afonso Coelho": ("Portugal", "Verified", "pt.linkedin.com/in/afonsoamorimcoelho; Portugal (Revolut Porto)"),
    "Revolut||Pietro Dalpane": ("United Kingdom", "Verified", "uk.linkedin.com/in/pietro-dalpane; #londontech"),

    # ---- Wise (UK HQ, distributed) ----
    "Wise||Nilan Peiris": ("United Kingdom", "Verified", "profile: London, GB"),
    "Wise||Josh Payton": ("United Kingdom", "Verified", "profile: London"),
    "Wise||Cian Weeresinghe": ("United Kingdom", "Verified", "profile: London, England, GB"),
    "Wise||Iona Carter": ("United Kingdom", "Verified", "uk.linkedin.com/in/iona-carter; VP Brand Wise"),
    "Wise||Alessandro Battaglia": ("United Kingdom", "Verified", "profile: United Kingdom"),
    "Wise||Ziggy Pragier": ("United Kingdom", "Verified", "profile: London"),
    "Wise||Samuele Erbi": ("United Kingdom", "Verified", "profile: United Kingdom"),
    "Wise||Magda Panfil": ("United Kingdom", "Assumed", "no clean match; Wise HQ (UK) default (Wise also has Tallinn/Budapest hubs)"),
    "Wise||Ruth Chadwick": ("United Kingdom", "Verified", "profile: United Kingdom"),
    "Wise||Mike Shebalkov": ("United Kingdom", "Verified", "profile: London"),
    "Wise||Ayesha Kadan": ("United Kingdom", "Assumed", "uk.linkedin; ex-Uber Amsterdam - possibly NL, unconfirmed"),
    "Wise||Sonia-Carla Ciocirlie": ("United Kingdom", "Verified", "profile: London, GB; UK Companies House officer"),
    "Wise||Chetna Shastry": ("United Kingdom", "Verified", "profile: United Kingdom"),
    "Wise||Samara Thomas": ("United Kingdom", "Verified", "uk.linkedin.com/in/samaraschulz; Wise London"),

    # ---- Monzo (UK bank, expanding to EU/Ireland) ----
    "Monzo||Natalie Malevsky": ("United Kingdom", "Verified", "profile: London, England, GB"),
    "Monzo||Nicole Christensen": ("United Kingdom", "Verified", "uk.linkedin.com/in/nicolechris; Monzo EU expansion, UK-based"),
    "Monzo||Jordan Shwide": ("United Kingdom", "Verified", "profile: London, GB"),
    "Monzo||Chris Mucklow-Norell": ("United Kingdom", "Verified", "profile: London"),
    "Monzo||Emily Suter": ("United Kingdom", "Verified", "uk.linkedin; Monzo London (Oxford grad)"),
    "Monzo||Rannie Powell": ("United Kingdom", "Assumed", "Monzo COO office (London); no explicit location"),
    "Monzo||Ben Lawrence": ("United Kingdom", "Verified", "uk.linkedin.com/in/benjlawrence; Monzo"),
    "Monzo||Arundhathi Desai": ("United Kingdom", "Verified", "profile: London, GB"),
    "Monzo||Shelley Malton": ("United Kingdom", "Verified", "uk.linkedin; ex-NatWest, Monzo Group COO"),
    "Monzo||Katie Brown": ("United Kingdom", "Verified", "profile: London, GB (Katie Gormley)"),
    "Monzo||Karen Addy": ("United Kingdom", "Verified", "uk.linkedin.com/in/karen-addy; Monzo"),
    "Monzo||Rachad Khoury": ("United Kingdom", "Verified", "profile: United Kingdom"),
    "Monzo||Katrina O'Donnell": ("United Kingdom", "Verified", "profile: London, England, GB"),
    "Monzo||Nicole Rudland": ("United Kingdom", "Assumed", "Monzo Customer Ops (Cardiff/London/Remote UK); no explicit location"),
    "Monzo||Rich Harris": ("United Kingdom", "Verified", "profile: London, GB"),

    # ---- Starling Bank (UK-only bank) ----
    "Starling Bank||Michele Rousseau": ("United Kingdom", "Verified", "profile: United Kingdom; Starling CMO"),
    "Starling Bank||Raghu Narula": ("United Kingdom", "Assumed", "ex-NatWest UK; Starling is UK-only; no explicit location"),
    "Starling Bank||Emma Stanning": ("United Kingdom", "Verified", "profile: United Kingdom"),
    "Starling Bank||Daniel Cosentino": ("United Kingdom", "Verified", "profile: London"),
    "Starling Bank||Lisa Cunico": ("United Kingdom", "Verified", "profile: United Kingdom"),
    "Starling Bank||Evangelos Rakovitis": ("United Kingdom", "Verified", "profile: London, GB"),
    "Starling Bank||Jessie Broome": ("United Kingdom", "Verified", "profile: United Kingdom (Jessie Harrington Broome)"),
    "Starling Bank||Joe Bakowski": ("United Kingdom", "Verified", "uk profile; ex-Metro Bank UK; Starling UK-only"),
    "Starling Bank||Chris Ross": ("United Kingdom", "Assumed", "no clean match; Starling is UK-only"),
    "Starling Bank||Indiana Matine": ("United Kingdom", "Verified", "profile: London, GB"),
    "Starling Bank||Luke Farrell": ("United Kingdom", "Verified", "profile: London"),
    "Starling Bank||Sami Kade": ("United Kingdom", "Assumed", "Starling UK-only; no explicit location on profile"),
    "Starling Bank||Aaron Shaw": ("United Kingdom", "Verified", "uk.linkedin.com/in/aarshaw; Starling"),

    # ---- N26 (Germany HQ, Berlin; international) ----
    "N26||Catalina Garcia": ("Spain", "Verified", "profile: Madrid, Spain; N26 Iberia marketing"),
    "N26||Covadonga Calvo": ("Germany", "Verified", "profile: Berlin, DE"),
    "N26||Laura Cristaldi": ("Germany", "Verified", "profile: Berlin Metropolitan Area"),
    "N26||Katharina Pollak": ("Germany", "Verified", "de.linkedin.com/in/katharina-pollak; N26 (Berlin)"),
    # -- N26 remaining: not searched (hit 200-search cap); HQ default (Berlin/Germany) --
    "N26||Luis Franqueira": ("Germany", "Assumed", "not searched (search cap); N26 Berlin HQ default"),
    "N26||Prithviraj Sarkar": ("Germany", "Assumed", "not searched (search cap); N26 Berlin HQ default"),
    "N26||Niklas Oertel": ("Germany", "Assumed", "not searched (search cap); title 'Head of Growth - Germany' -> Germany"),
    "N26||Pierre Plessis": ("Germany", "Assumed", "not searched (search cap); no email; N26 Berlin HQ default"),
    "N26||Will Sorby": ("Germany", "Assumed", "not searched (search cap); N26 Berlin HQ default"),
    "N26||Crystal Goh": ("Germany", "Assumed", "not searched (search cap); N26 Berlin HQ default"),
    "N26||Holger Boehmer": ("Germany", "Assumed", "not searched (search cap); MD N26 Operations GmbH -> Germany"),
    "N26||Siddharth Paul": ("Germany", "Assumed", "not searched (search cap); N26 Berlin HQ default"),
    "N26||Christopher Poots": ("Germany", "Assumed", "not searched (search cap); N26 Berlin HQ default"),

    # ---- Trade Republic (Germany HQ, Berlin) - not searched (hit 200-search cap); HQ default ----
    "Trade Republic||Marcus Letsch": ("Germany", "Assumed", "not searched (search cap); TR Berlin HQ default"),
    "Trade Republic||Nina Jetter-Schmidt": ("Germany", "Assumed", "not searched (search cap); TR Berlin HQ default"),
    "Trade Republic||Alexander Blum": ("Germany", "Assumed", "not searched (search cap); TR Berlin HQ default"),
    "Trade Republic||Julian Collin": ("Germany", "Assumed", "not searched (search cap); 'GM International Markets' - HQ default, may differ"),
    "Trade Republic||Ulrich Schroeer": ("Germany", "Assumed", "not searched (search cap); TR Berlin HQ default"),
    "Trade Republic||Daniel Tordable": ("Germany", "Assumed", "not searched (search cap); TR Berlin HQ default"),
    "Trade Republic||Kirill Novikov": ("Germany", "Assumed", "not searched (search cap); TR Berlin HQ default"),
    "Trade Republic||Ghazal Azari": ("Germany", "Assumed", "not searched (search cap); TR Berlin HQ default"),
    "Trade Republic||Dora Trostanetsky": ("Germany", "Assumed", "not searched (search cap); TR Berlin HQ default"),
    "Trade Republic||Felix Jamestin": ("Germany", "Assumed", "not searched (search cap); TR Berlin HQ default"),
    "Trade Republic||Laura Eggers": ("Germany", "Assumed", "not searched (search cap); TR Berlin HQ default"),
    "Trade Republic||Victor Kovatsenko": ("Germany", "Assumed", "not searched (search cap); TR Berlin HQ default"),
}
